version: 2

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - examples

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck

issues:
  # Exclude defer close errors as they are generally safe to ignore
  exclude-rules:
    - text: "Error return value.*defer.*Close"
      linters:
        - errcheck
    - text: "Error return value.*defer.*Remove"
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0
