version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: standard
  disable:
    - errcheck
  exclusions:
    paths:
      - examples

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
